eval_name: video_classification_frozen
folder: /home/sp/sp/jepa/evals_2_1/
tag: anomaly-16x3x3
num_workers: 8

experiment:
  classifier:
    num_heads: 16
    num_probe_blocks: 4
  data:
    dataset_type: VideoDataset
    dataset_train: /home/sp/sp/jepa/datasets/train.csv
    dataset_val: /home/sp/sp/jepa/datasets/val.csv
    frame_step: 4
    frames_per_clip: 16
    num_classes: 2
    num_segments: 5
    num_views_per_segment: 3
    resolution: 384
  optimization:
    batch_size: 2
    multihead_kwargs:
      - final_lr: 0.0
        final_weight_decay: 0.01
        lr: 0.005
        start_lr: 0.005
        warmup: 0.0
        weight_decay: 0.01
      - final_lr: 0.0
        final_weight_decay: 0.01
        lr: 0.003
        start_lr: 0.003
        warmup: 0.0
        weight_decay: 0.01
      - final_lr: 0.0
        final_weight_decay: 0.01
        lr: 0.001
        start_lr: 0.001
        warmup: 0.0
        weight_decay: 0.01
      - final_lr: 0.0
        final_weight_decay: 0.01
        lr: 0.0003
        start_lr: 0.0003
        warmup: 0.0
        weight_decay: 0.01
      - final_lr: 0.0
        final_weight_decay: 0.01
        lr: 0.0001
        start_lr: 0.0001
        warmup: 0.0
        weight_decay: 0.01
      - final_lr: 0.0
        final_weight_decay: 0.1
        lr: 0.005
        start_lr: 0.005
        warmup: 0.0
        weight_decay: 0.1
      - final_lr: 0.0
        final_weight_decay: 0.1
        lr: 0.003
        start_lr: 0.003
        warmup: 0.0
        weight_decay: 0.1
      - final_lr: 0.0
        final_weight_decay: 0.1
        lr: 0.001
        start_lr: 0.001
        warmup: 0.0
        weight_decay: 0.1
      - final_lr: 0.0
        final_weight_decay: 0.1
        lr: 0.0003
        start_lr: 0.0003
        warmup: 0.0
        weight_decay: 0.1
      - final_lr: 0.0
        final_weight_decay: 0.1
        lr: 0.0001
        start_lr: 0.0001
        warmup: 0.0
        weight_decay: 0.1
      - final_lr: 0.0
        final_weight_decay: 0.4
        lr: 0.005
        start_lr: 0.005
        warmup: 0.0
        weight_decay: 0.4
      - final_lr: 0.0
        final_weight_decay: 0.4
        lr: 0.003
        start_lr: 0.003
        warmup: 0.0
        weight_decay: 0.4
      - final_lr: 0.0
        final_weight_decay: 0.4
        lr: 0.001
        start_lr: 0.001
        warmup: 0.0
        weight_decay: 0.4
      - final_lr: 0.0
        final_weight_decay: 0.4
        lr: 0.0003
        start_lr: 0.0003
        warmup: 0.0
        weight_decay: 0.4
      - final_lr: 0.0
        final_weight_decay: 0.4
        lr: 0.0001
        start_lr: 0.0001
        warmup: 0.0
        weight_decay: 0.4
      - final_lr: 0.0
        final_weight_decay: 0.8
        lr: 0.005
        start_lr: 0.005
        warmup: 0.0
        weight_decay: 0.8
      - final_lr: 0.0
        final_weight_decay: 0.8
        lr: 0.003
        start_lr: 0.003
        warmup: 0.0
        weight_decay: 0.8
      - final_lr: 0.0
        final_weight_decay: 0.8
        lr: 0.001
        start_lr: 0.001
        warmup: 0.0
        weight_decay: 0.8
      - final_lr: 0.0
        final_weight_decay: 0.8
        lr: 0.0003
        start_lr: 0.0003
        warmup: 0.0
        weight_decay: 0.8
      - final_lr: 0.0
        final_weight_decay: 0.8
        lr: 0.0001
        start_lr: 0.0001
        warmup: 0.0
        weight_decay: 0.8
    num_epochs: 30
    use_bfloat16: true
    use_pos_embed: false

model_kwargs:
  checkpoint: pretrained/vjepa2_1_vitb_dist_vitG_384.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: ema_encoder
      img_temporal_dim_size: 1
      model_name: vit_base
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
